name: appliedautonomy-uc-test
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Test Ubuntu Core snap built on C and make # 79 char long summary
description: |
  Test snap for Ubuntu Core built on C with make for RPi

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: armhf
    run-on: armhf

apps:
  appliedautonomy-uc-test:
    command: mytest
    plugs: [gpio-memory-control, io-ports-control]
    
parts:
  my-part:
    plugin: make
    source: .
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp mytest $SNAPCRAFT_PART_INSTALL/bin/mytest