name: appliedautonomy-uc-test
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Test Ubuntu Core snap for MQTT telemetry # 79 char long summary
description: |
  Test snap for Ubuntu Core built in C/C++ for RPi B+
  It reads GPIO21 and sends it to Google Cloud IoT Core MQTT bridge
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: armhf
    run-on: armhf

apps:
  appliedautonomy-uc-test:
    command: mqtt-telemetry
    plugs: [gpio-memory-control]
    
parts:
  my-part:
    plugin: make
    source: .
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp mqtt-telemetry $SNAPCRAFT_PART_INSTALL/bin/mqtt-telemetry